Repository geoadmin/service-stac, pull requests merged in 2021-11, with the labels that each got.

#320 BGDIINF_SB-1983: `md5_parts` is now a mandatory parameter
  .pylintrc
  app/stac_api/apps.py
  app/stac_api/managers.py
  app/stac_api/models.py
  app/stac_api/pagination.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/validators_serializer.py
  app/stac_api/validators_view.py
  app/stac_api/views.py
  app/stac_api/views_mixins.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_asset_upload_model.py
  app/tests/test_generic_api.py
  app/tests/test_serializer.py
  app/tests/test_serializer_asset_upload.py
  app/tests/test_validators.py
Labels: feature

#322 BGDIINF_SB-2033: adding generic zip media type
  app/stac_api/validators.py
Labels: feature

#323 New Relase v1.8.0
  .github/workflows/main.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/semver.yml
  .pylintrc
  README.md
  app/stac_api/apps.py
  app/stac_api/managers.py
  app/stac_api/models.py
  app/stac_api/pagination.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/validators.py
  app/stac_api/validators_serializer.py
  app/stac_api/validators_view.py
  app/stac_api/views.py
  app/stac_api/views_mixins.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_asset_upload_model.py
  app/tests/test_generic_api.py
  app/tests/test_serializer.py
  app/tests/test_serializer_asset_upload.py
  app/tests/test_validators.py
Labels: new-release

#325 Add PR auto Title Workflow and updated PR labeler
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-semver-release-title.yml
Labels: skip-release-note

#326 Consolidate PR workflows
  .github/workflows/pr-auto-semver.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/semver.yml
Labels: skip-release-note

#327 Renamed the workflow templates
  .github/workflows/pr-auto-semver.yml
  .github/workflows/semver.yml
Labels: skip-release-note
