Repository geoadmin/service-stac, pull requests merged in 2022-02, with the labels that each got.

#334 BGDIINF_SB-2163: Fixed CI branch name resolution
  buildspec.yml
Labels: bug

#335 BGDIINF_SB-2196: Order collections by title
  app/stac_api/views.py
  app/tests/test_collections_endpoint.py
  app/tests/test_generic_api.py
  spec/Makefile
Labels: feature

#338 BGDIINF_SB-2210: Changed the STAC Browser links for Browser v3
  Pipfile
  Pipfile.lock
  app/stac_api/utils.py
Labels: feature

#339 BGDIINF_SB-2210: Fixed the STAC Browser links v3
  app/stac_api/serializers_utils.py
  app/stac_api/utils.py
  app/tests/test_collections_summaries.py
Labels: feature

#336 New Release v1.9.0 - #minor
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  adr/2020_08_13_application_architecture.md
  app/stac_api/serializers_utils.py
  app/stac_api/utils.py
  app/stac_api/views.py
  app/tests/test_collections_endpoint.py
  app/tests/test_collections_summaries.py
  app/tests/test_generic_api.py
  buildspec.yml
  scripts/create_dummy_asset_for_multipart_testing.py
  scripts/multipart_upload_via_api.py
  scripts/secrets.yml
  scripts/upsert_asset_via_api.py
  spec/Makefile
Labels: new-release
