Repository geoadmin/service-stac, pull requests merged in 2023-02, with the labels that each got.

#355 BGDIINF_SB-2693: update to python 3.9 and dependencies
  .pylintrc
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/config/logging-cfg-local.yml
  app/config/logging-cfg-management.yml
  app/config/logging-cfg-unittest-ci.yml
  app/config/logging-cfg-unittest.yml
  app/config/settings_prod.py
  app/config/settings_test.py
  app/config/urls.py
  app/manage.py
  app/stac_api/admin.py
  app/stac_api/management/commands/write_perftests.py
  app/stac_api/migrations/0022_asset_update_asset_collection_summaries_trigger_and_more.py
  app/stac_api/models.py
  app/stac_api/pgtriggers.py
  app/stac_api/sample_data/importer.py
  app/stac_api/serializers.py
  app/stac_api/utils.py
  app/tests/data_factory.py
  app/tests/test_conformance.py
  app/tests/test_generic_api.py
  app/tests/test_healthcheck.py
  app/tests/test_sampledata.py
  app/tests/test_serializer.py
  app/wsgi.py
  buildspec.yml
  docker-compose-ci.yml
  update_to_latest.sh
Labels: feature

#358 BGDIINF_SB-2714: Dockerfile now sets worker_tmp_dir
  Dockerfile
  docker-compose-ci.yml
Labels: feature

#359 BGDIINF_SB-2707: Now serializer is more permissive with mime types
  app/stac_api/management/commands/write_perftests.py
  app/stac_api/models.py
  app/stac_api/serializers.py
  app/stac_api/validators.py
  app/tests/data_factory.py
  app/tests/sample_data/asset_samples.py
  app/tests/test_asset_model.py
  app/tests/test_assets_endpoint.py
  app/tests/test_validators.py
Labels: bug

#360 New Release v1.15.0 - #minor
  .pylintrc
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/config/logging-cfg-local.yml
  app/config/logging-cfg-management.yml
  app/config/logging-cfg-unittest-ci.yml
  app/config/logging-cfg-unittest.yml
  app/config/settings_prod.py
  app/config/settings_test.py
  app/config/urls.py
  app/manage.py
  app/stac_api/admin.py
  app/stac_api/management/commands/write_perftests.py
  app/stac_api/migrations/0022_asset_update_asset_collection_summaries_trigger_and_more.py
  app/stac_api/models.py
  app/stac_api/pgtriggers.py
  app/stac_api/sample_data/importer.py
  app/stac_api/serializers.py
  app/stac_api/utils.py
  app/stac_api/validators.py
  app/tests/data_factory.py
  app/tests/sample_data/asset_samples.py
  app/tests/test_asset_model.py
  app/tests/test_assets_endpoint.py
  app/tests/test_conformance.py
  app/tests/test_generic_api.py
  app/tests/test_healthcheck.py
  app/tests/test_sampledata.py
  app/tests/test_serializer.py
  app/tests/test_validators.py
  app/wsgi.py
  buildspec.yml
  docker-compose-ci.yml
  update_to_latest.sh
Labels: new-release

#361 BGDIINF_SB-2371: Migrate buildspec in CI infrastructure
  Dockerfile
  buildspec.yml
Labels: feature

#362 BGDIINF_SB-2799: ADR Cache settings
  adr/2023_02_27_cache_settings.md
Labels: feature
