Repository geoadmin/service-stac, pull requests merged in 2023-03, with the labels that each got.

#363 BGDIINF_SB-2707: Added missing migration files
  README.md
  app/config/settings_prod.py
  app/stac_api/migrations/0023_alter_asset_media_type.py
Labels: feature

#365 BGDIINF_SB-2799: Added dynamic cache settings
  Pipfile.lock
  README.md
  app/config/settings_prod.py
  app/middleware/cache_headers.py
  app/stac_api/admin.py
  app/stac_api/migrations/0024_added_update_interval_field.py
  app/stac_api/models.py
  app/stac_api/pgtriggers.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/storages.py
  app/stac_api/utils.py
  app/stac_api/views.py
  app/stac_api/views_mixins.py
  app/tests/base_test.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_assets_endpoint.py
  app/tests/test_collections_endpoint.py
  app/tests/test_generic_api.py
  app/tests/test_items_endpoint.py
  app/tests/test_landing_page.py
  app/tests/test_pgtriggers.py
  app/tests/utils.py
Labels: feature

#366 BGDIINF_SB-2799: Updated ADR for cache settings
  adr/2023_02_27_cache_settings.md
  adr/cache-control-vs-update_interval-graph.png
Labels: feature

#368 Fixed gunicorn tmp dir worker
  Dockerfile
Labels: bug

#364 BGDIINF_SB-2799: added docu about asset object caching behaviour
  spec/components/parameters.yaml
  spec/components/responses.yaml
  spec/components/schemas.yaml
  spec/openapi.yaml
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: feature

#369 BGDIINF_SB-2799: Fixed static files serving and clean up environment variables
  .dockerignore
  .env.default
  Dockerfile
  Makefile
  README.md
  app/config/logging-cfg-local.yml
  app/config/logging-cfg-management.yml
  app/config/logging-cfg-unittest-ci.yml
  app/config/logging-cfg-unittest.yml
  app/config/settings_prod.py
  app/manage.py
  app/middleware/debug.py
  app/stac_api/management/commands/profile_cursor_paginator.py
  app/stac_api/management/commands/profile_item_serializer.py
  docker-compose-ci.yml
  docker-compose.yml
Labels: feature

#367 Fixed `manage.py dummy data clean` command
  app/stac_api/management/commands/dummy_data.py
Labels: bug

#371 BGDIINF_SB-2799: Fixed Spec transactional part being in public part
  Dockerfile
  spec/components/parameters.yaml
  spec/openapi.yaml
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/paths.yaml
Labels: bug

#373 BGDIINF_SB-2799: Fixed performance issue with the search endpoint due to update_interval
  app/stac_api/views.py
  app/tests/test_search_endpoint.py
Labels: bug

#375 BGDIINF_SB-2806: Added more checks to be performed by CI
  Makefile
  docker-compose-ci.yml
  docker-compose.yml
Labels: feature

#376 BGDIINF_SB-2827: Removed auto abort asset upload on duplicate upload to fix integrity crash
  app/stac_api/views.py
  app/tests/base_test.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/utils.py
Labels: bug

#381 BGDIINF_SB-2835: Added content_encoding in spec for asset upload
  spec/components/headers.yaml
  spec/components/parameters.yaml
  spec/components/responses.yaml
  spec/components/schemas.yaml
  spec/openapi.yaml
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/examples.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: feature

#383 BGDIINF_SB-2813: Fixed collection pagination
  README.md
  app/stac_api/management/commands/dummy_data.py
  app/stac_api/views.py
  app/tests/test_collections_endpoint.py
Labels: bug

#382 BGDIINF_SB-2835: Added content_encoding param to API Asset Upload
  app/stac_api/admin.py
  app/stac_api/migrations/0026_add_asset_upload_content_encoding.py
  app/stac_api/models.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/validators.py
  app/stac_api/views.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_generic_api.py
  app/tests/test_serializer_asset_upload.py
  app/tests/test_validators.py
  app/tests/utils.py
Labels: feature

#385 New Release v1.18.0 - #minor
  README.md
  app/stac_api/admin.py
  app/stac_api/management/commands/dummy_data.py
  app/stac_api/migrations/0026_add_asset_upload_content_encoding.py
  app/stac_api/models.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/validators.py
  app/stac_api/views.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_collections_endpoint.py
  app/tests/test_generic_api.py
  app/tests/test_serializer_asset_upload.py
  app/tests/test_validators.py
  app/tests/utils.py
  spec/components/headers.yaml
  spec/components/parameters.yaml
  spec/components/responses.yaml
  spec/components/schemas.yaml
  spec/openapi.yaml
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/examples.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: new-release

#387 BGDIINF_SB-2158: add local prefix in docker build
  Makefile
Labels: feature
