Repository geoadmin/service-stac, pull requests merged in 2023-06, with the labels that each got.

#393 BGDIINF_SB-2924 adapt log level for better debugging - #patch
  app/middleware/logging.py
Labels: bug

#396 BGDIINF_SB-2924: Fixed duplicate asset upload complete issue
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/views.py
  app/tests/test_asset_upload_endpoint.py
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/paths.yaml
Labels: bug

#395 BGDIINF_SB-2924: Added docu about asset upload error handling.
  doc/assets/service-stac-upload-process.dia
  doc/assets/service-stac-upload-process.svg
  doc/stac-upload-error-handling.md
Labels: feature

#397 New Release v1.20.0 - #minor
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/utils.py
  app/stac_api/views.py
  app/tests/test_asset_upload_endpoint.py
  app/tests/test_items_endpoint.py
  app/tests/test_items_endpoint_bbox.py
  doc/assets/service-stac-upload-process.dia
  doc/assets/service-stac-upload-process.svg
  doc/stac-upload-error-handling.md
  spec/static/spec/v0.9/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/paths.yaml
Labels: new-release
