Repository geoadmin/service-stac, pull requests merged in 2024-12, with the labels that each got.

#479 PB-1252: BigIntegerField for asset file size
  app/stac_api/migrations/0055_alter_asset_file_size_alter_assetupload_file_size_and_more.py
  app/stac_api/migrations/0056_alter_collection_total_data_size_and_more.py
  app/stac_api/models.py
Labels: bug

#480 New Release v1.28.2 - #patch
  Dockerfile
  app/stac_api/migrations/0055_alter_asset_file_size_alter_assetupload_file_size_and_more.py
  app/stac_api/migrations/0056_alter_collection_total_data_size_and_more.py
  app/stac_api/models.py
Labels: new-release

#477 PB-1073 Implement forecast extension
  app/stac_api/admin.py
  app/stac_api/migrations/0057_item_forecast_duration_item_forecast_horizon_and_more.py
  app/stac_api/models.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/utils.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_serializer.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/paths.yaml
Labels: feature

#481 Make session tracking work with API Gateway.
  app/config/settings_dev.py
  app/middleware/apigw.py
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
Labels: bug

#482 PB-1009: simplify ApiGatewayMiddleware.
  app/middleware/apigw.py
Labels: bug

#483 PB-1157 Add hreflang to Links
  Pipfile
  Pipfile.lock
  app/stac_api/admin.py
  app/stac_api/migrations/0058_collectionlink_hreflang_itemlink_hreflang_and_more.py
  app/stac_api/models.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/utils.py
  app/tests/tests_10/data_factory.py
  app/tests/tests_10/sample_data/collection_samples.py
  app/tests/tests_10/sample_data/item_samples.py
  app/tests/tests_10/test_collections_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
Labels: feature

#484 PB-1091 Add count to size updater, exclude is_external
  app/stac_api/management/commands/update_asset_file_size.py
Labels: feature

#486 New Release v1.29.0 - #minor
  Pipfile
  Pipfile.lock
  app/config/settings_dev.py
  app/middleware/apigw.py
  app/stac_api/admin.py
  app/stac_api/management/commands/update_asset_file_size.py
  app/stac_api/migrations/0057_item_forecast_duration_item_forecast_horizon_and_more.py
  app/stac_api/migrations/0058_collectionlink_hreflang_itemlink_hreflang_and_more.py
  app/stac_api/models.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/utils.py
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
  app/tests/tests_10/data_factory.py
  app/tests/tests_10/sample_data/collection_samples.py
  app/tests/tests_10/sample_data/item_samples.py
  app/tests/tests_10/test_collections_endpoint.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_serializer.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/paths.yaml
Labels: new-release

#487 PB-1293 Add docs for endpoint bulkUpsertItems
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: feature
