Repository geoadmin/service-stac, pull requests merged in 2024-09, with the labels that each got.

#454 PB-511: Add request context to all logs
  Pipfile
  Pipfile.lock
  app/config/logging-cfg-local.yml
  app/config/settings_prod.py
Labels: feature

#455 PB-755: Spec for collection assets
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: feature

#457 New Release v1.26.0 - #minor
  Pipfile
  Pipfile.lock
  app/config/logging-cfg-local.yml
  app/config/settings_prod.py
  app/stac_api/management/commands/remove_expired_items.py
  app/stac_api/utils.py
  app/stac_api/validators.py
  app/stac_api/validators_view.py
  app/stac_api/views.py
  app/tests/test_admin_page.py
  app/tests/tests_09/test_item_model.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_remove_expired_items.py
  docker-compose.yml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: new-release

#459 PB-932: Avoid UTF-8 truncation in logging
  app/middleware/logging.py
Labels: bug

#460 New Release v1.27.0 - #minor
  app/config/urls.py
  app/middleware/logging.py
  app/stac_api/management/commands/list_asset_uploads.py
  app/stac_api/management/commands/profile_item_serializer.py
  app/stac_api/management/commands/profile_serializer_vs_no_drf.py
  app/stac_api/migrations/0050_collectionassetupload_and_more.py
  app/stac_api/models.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers.py
  app/stac_api/serializers/__init__.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/general.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/upload.py
  app/stac_api/serializers/utils.py
  app/stac_api/signals.py
  app/stac_api/urls.py
  app/stac_api/validators_view.py
  app/stac_api/views.py
  app/stac_api/views/__init__.py
  app/stac_api/views/collection.py
  app/stac_api/views/general.py
  app/stac_api/views/item.py
  app/stac_api/views/mixins.py
  app/stac_api/views/test.py
  app/stac_api/views/upload.py
  app/tests/tests_09/test_serializer.py
  app/tests/tests_09/test_serializer_asset_upload.py
  app/tests/tests_10/base_test.py
  app/tests/tests_10/data_factory.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_model.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  app/tests/tests_10/test_serializer.py
  app/tests/tests_10/test_serializer_asset_upload.py
  scripts/fill_local_db.py
Labels: new-release

#462 PB-796: remove CommonMiddlewareWithInternalRedirect.
  app/config/admin.py
  app/config/settings_prod.py
  app/middleware/internal_redirect.py
  app/tests/test_admin_page.py
  app/tests/tests_09/test_landing_page.py
  app/tests/tests_10/test_landing_page.py
Labels: feature
