Repository geoadmin/service-stac, pull requests merged in 2024-11, with the labels that each got.

#468 Fix spec asset href
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: bug

#469 PB-1071: add new mime types for Zipped LAS and Cloud Optimized Point
  app/stac_api/migrations/0053_alter_asset_media_type_and_more.py
  app/stac_api/validators.py
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/tags.yaml
Labels: feature

#465 PB-987: Add item-search to conformance endpoint
  Makefile
  app/stac_api/migrations/0054_update_conformance_endpoint.py
Labels: feature

#470 PB-1008 Test the ch.are pattern
  app/tests/test_multiple_bucket_setup.py
Labels: feature

#471 PB-1009: trust API Gateway to authenticate users.
  app/config/settings_dev.py
  app/middleware/apigw.py
  app/tests/test_admin_page.py
Labels: feature

#472 PB-224: Added a query parameter on the /collections route to filter by provider
  app/stac_api/views/collection.py
  spec/components/parameters.yaml
  spec/openapi.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
Labels: feature

#473 New Release v1.28.0 - #minor
  .env.default
  Makefile
  README.md
  app/config/admin.py
  app/config/settings_dev.py
  app/config/settings_prod.py
  app/middleware/apigw.py
  app/middleware/internal_redirect.py
  app/stac_api/admin.py
  app/stac_api/management/commands/update_asset_file_size.py
  app/stac_api/migrations/0051_asset_file_size_assetupload_file_size_and_more.py
  app/stac_api/migrations/0052_asset_add_del_asset_item_file_size_trigger_and_more.py
  app/stac_api/migrations/0053_alter_asset_media_type_and_more.py
  app/stac_api/migrations/0054_update_conformance_endpoint.py
  app/stac_api/models.py
  app/stac_api/pgtriggers.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/validators.py
  app/stac_api/views/collection.py
  app/stac_api/views/item.py
  app/stac_api/views/upload.py
  app/tests/test_admin_page.py
  app/tests/test_multiple_bucket_setup.py
  app/tests/tests_09/test_asset_upload_endpoint.py
  app/tests/tests_09/test_landing_page.py
  app/tests/tests_09/test_pgtriggers.py
  app/tests/tests_10/test_asset_upload_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_landing_page.py
  app/tests/tests_10/test_pgtriggers.py
  docker-compose.yml
  secrets.yml
  spec/components/parameters.yaml
  spec/openapi.yaml
  spec/static/spec/v0.9/openapitransactional.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: new-release

#474 PB-224: Added unit test to test new provider filtering functionality
  app/tests/tests_10/test_collections_endpoint.py
Labels: bug

#478 PB-1238: include static files in debug image.
  Dockerfile
Labels: bug
