Repository geoadmin/service-stac, pull requests merged in 2025-03, with the labels that each got.

#522 PB-1469: use v0.9 for large uploads from admin UI.
  app/stac_api/templates/js/admin/upload.js
Labels: bug

#531 Updated all paths from v0.9 to v1 in openapi spec
  spec/components/responses.yaml
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: feature

#529 PB-1469: fix charset conversion for large file upload.
  app/stac_api/templates/js/admin/upload.js
Labels: bug

#532 Make large uploads a little more useable.
  app/stac_api/templates/js/admin/upload.js
  app/templates/uploadtemplate.html
Labels: bug

#523 PB-1434 : removal of the 'file' attribute & small file uploads from admin UI
  app/stac_api/admin.py
  app/stac_api/models/general.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/templates/style/hover.css
  app/stac_api/widgets/label_widget.py
  app/templates/admin/change_form.html
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
Labels: bug

#534 Allow to use docker compose up directly
  docker-compose.yml
Labels: feature

#536 Fixed E2E tests for the localhost
  .env.default
Labels: bug

#535 PB-1434 : removal of the 'file' attribute & small file uploads from admin
  app/stac_api/admin.py
  app/stac_api/models/general.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/templates/style/hover.css
  app/stac_api/widgets/label_widget.py
  app/templates/admin/change_form.html
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
Labels: bug

#539 PB-124: Made the media type and Id fields on Asset not editable
  app/stac_api/admin.py
  app/stac_api/migrations/0064_alter_asset_media_type_and_more.py
  app/stac_api/models/general.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/item.py
  app/stac_api/views/item.py
  app/stac_api/views/mixins.py
  app/tests/test_admin_page.py
  app/tests/tests_09/test_assets_endpoint.py
  app/tests/tests_10/data_factory.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
Labels: bug

#541 PB-1492: Made all optional item properties nullable in PATCH
  app/stac_api/serializers/item.py
  app/tests/tests_09/test_items_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: bug

#540 PB-1434 : Add back 'file' field to Collections and CollectionAssets
  app/stac_api/admin.py
  app/stac_api/models/collection.py
  app/stac_api/widgets/label_widget.py
Labels: bug

#542 New Release v1.33.0 - #minor
  .env.default
  .gitignore
  .vscode/settings.json
  app/config/logging-cfg-local.yml
  app/config/settings_prod.py
  app/middleware/api_gateway_middleware.py
  app/stac_api/admin.py
  app/stac_api/migrations/0063_collection_cache_control_header.py
  app/stac_api/migrations/0064_alter_asset_media_type_and_more.py
  app/stac_api/models/collection.py
  app/stac_api/models/general.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/utils.py
  app/stac_api/templates/js/admin/upload.js
  app/stac_api/templates/style/hover.css
  app/stac_api/utils.py
  app/stac_api/validators.py
  app/stac_api/views/item.py
  app/stac_api/views/mixins.py
  app/templates/admin/change_form.html
  app/templates/uploadtemplate.html
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
  app/tests/tests_09/test_assets_endpoint.py
  app/tests/tests_09/test_geoadmin_header_auth.py
  app/tests/tests_09/test_items_endpoint.py
  app/tests/tests_10/base_test.py
  app/tests/tests_10/data_factory.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  app/tests/tests_10/test_geoadmin_header_auth.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_serializer.py
  app/tests/tests_10/test_validators.py
  docker-compose.yml
  spec/components/parameters.yaml
  spec/components/responses.yaml
  spec/components/schemas.yaml
  spec/openapi.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/responses.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: new-release

#538 PB-1126: Added E2E tests fixture
  app/tests/fixtures/README.md
  app/tests/fixtures/e2e-tests.json
Labels: feature

#527 PB-1126: Removed the update_interval field from item and collections model
  adr/2025_03_04_cache_settings_update.md
  app/config/settings_prod.py
  app/stac_api/admin.py
  app/stac_api/management/commands/dummy_asset_upload.py
  app/stac_api/migrations/0065_remove_asset_add_del_asset_item_update_interval_trigger_and_more.py
  app/stac_api/models/collection.py
  app/stac_api/models/general.py
  app/stac_api/models/item.py
  app/stac_api/pgtriggers.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/storages.py
  app/stac_api/utils.py
  app/stac_api/views/collection.py
  app/stac_api/views/general.py
  app/stac_api/views/item.py
  app/stac_api/views/mixins.py
  app/stac_api/views/upload.py
  app/tests/test_multiple_bucket_setup.py
  app/tests/tests_09/test_asset_upload_endpoint.py
  app/tests/tests_09/test_generic_api.py
  app/tests/tests_09/test_pgtriggers.py
  app/tests/tests_09/test_search_endpoint.py
  app/tests/tests_10/test_asset_upload_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_generic_api.py
  app/tests/tests_10/test_pgtriggers.py
  app/tests/tests_10/test_search_endpoint.py
  app/tests/tests_10/test_utils.py
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
Labels: feature

#544 New Release v1.34.0 - #minor
  adr/2025_03_04_cache_settings_update.md
  app/config/settings_prod.py
  app/stac_api/admin.py
  app/stac_api/management/commands/dummy_asset_upload.py
  app/stac_api/migrations/0065_remove_asset_add_del_asset_item_update_interval_trigger_and_more.py
  app/stac_api/models/collection.py
  app/stac_api/models/general.py
  app/stac_api/models/item.py
  app/stac_api/pgtriggers.py
  app/stac_api/s3_multipart_upload.py
  app/stac_api/serializers/item.py
  app/stac_api/storages.py
  app/stac_api/utils.py
  app/stac_api/validators.py
  app/stac_api/views/collection.py
  app/stac_api/views/general.py
  app/stac_api/views/item.py
  app/stac_api/views/mixins.py
  app/stac_api/views/upload.py
  app/tests/fixtures/README.md
  app/tests/fixtures/e2e-tests.json
  app/tests/test_multiple_bucket_setup.py
  app/tests/tests_09/test_asset_upload_endpoint.py
  app/tests/tests_09/test_generic_api.py
  app/tests/tests_09/test_pgtriggers.py
  app/tests/tests_09/test_search_endpoint.py
  app/tests/tests_09/test_validators.py
  app/tests/tests_10/test_asset_upload_endpoint.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_generic_api.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_pgtriggers.py
  app/tests/tests_10/test_remove_expired_items.py
  app/tests/tests_10/test_search_endpoint.py
  app/tests/tests_10/test_utils.py
  app/tests/tests_10/test_validators.py
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
Labels: new-release

#551 PB-1515 : add big asset upload to the collection asset
  app/stac_api/admin.py
  app/stac_api/templates/js/admin/upload.js
  app/stac_api/urls.py
Labels: bug

#555 New Release v1.35.0 - #minor
  .env.default
  .vscode/launch.json
  app/config/settings_prod.py
  app/config/settings_test.py
  app/middleware/api_gateway_middleware.py
  app/middleware/logging.py
  app/stac_api/admin.py
  app/stac_api/migrations/0066_collectionasset_is_external.py
  app/stac_api/models/collection.py
  app/stac_api/serializers/collection.py
  app/stac_api/serializers/item.py
  app/stac_api/serializers/utils.py
  app/stac_api/templates/js/admin/asset_external_fields.js
  app/stac_api/templates/js/admin/asset_help_search.js
  app/stac_api/templates/js/admin/collection_help_search.js
  app/stac_api/templates/js/admin/item_help_search.js
  app/stac_api/templates/js/admin/upload.js
  app/stac_api/templates/style/hover.css
  app/stac_api/urls.py
  app/stac_api/validators.py
  app/stac_api/views/collection.py
  app/stac_api/views/item.py
  app/tests/test_middlewares.py
  app/tests/tests_09/test_serializer.py
  app/tests/tests_10/base_test.py
  app/tests/tests_10/sample_data/asset_samples.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  app/tests/tests_10/test_external_collection_assets_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_serializer.py
Labels: new-release
