Repository geoadmin/service-stac, pull requests merged in 2025-01, with the labels that each got.

#489 added grib media type for MCH
  app/stac_api/migrations/0059_alter_asset_media_type_and_more.py
  app/stac_api/validators.py
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/tags.yaml
Labels: feature

#490 PB-986 Cleanup obsolete SQL management scripts
  README.md
  scripts/setup_rds_db.sh
  scripts/sql/create_db.sql
  scripts/sql/create_user.sql
  scripts/sql/install_postgis.sql
  scripts/sql/load_random_data.sql
  secrets.yml
Labels: feature

#493 PB-1321 adapted fieldnames and spec to comply to forecast extension
  app/stac_api/admin.py
  app/stac_api/migrations/0060_item_forecast_perturbed_item_forecast_variable.py
  app/stac_api/migrations/0061_remove_item_forecast_mode_remove_item_forecast_param_and_more.py
  app/stac_api/models.py
  app/stac_api/serializers/item.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_serializer.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/paths.yaml
Labels: feature

#494 PB-931 Update logging-utilities to 5.0.0
  Pipfile
  Pipfile.lock
Labels: feature

#495 Regenerate the specs.
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
Labels: bug

#497 PB-1091 Flag the inexistent files in the file size updater
  app/stac_api/management/commands/update_asset_file_size.py
Labels: feature

#498 New Release v1.30.0 - #minor
  .gitignore
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  app/stac_api/admin.py
  app/stac_api/management/commands/dummy_asset_upload.py
  app/stac_api/management/commands/remove_expired_items.py
  app/stac_api/management/commands/update_asset_file_size.py
  app/stac_api/migrations/0059_alter_asset_media_type_and_more.py
  app/stac_api/migrations/0060_item_forecast_perturbed_item_forecast_variable.py
  app/stac_api/migrations/0061_remove_item_forecast_mode_remove_item_forecast_param_and_more.py
  app/stac_api/models.py
  app/stac_api/serializers/item.py
  app/stac_api/validators.py
  app/tests/tests_10/test_item_model.py
  app/tests/tests_10/test_serializer.py
  scripts/setup_rds_db.sh
  scripts/sql/create_db.sql
  scripts/sql/create_user.sql
  scripts/sql/install_postgis.sql
  scripts/sql/load_random_data.sql
  secrets.yml
  spec/Makefile
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/parameters.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: new-release

#501 PB-1281: Add feature flag for ApiGateway authentication
  app/config/settings_dev.py
  app/config/settings_prod.py
  app/middleware/apigw.py
  app/tests/test_admin_page.py
Labels: feature

#499 using GET range request instead of HEAD to check external asset reach…
  app/stac_api/validators.py
  app/tests/tests_10/test_external_assets_endpoint.py
Labels: feature

#502 PB-1366: make new auth work for write requests.
  app/config/settings_prod.py
  app/middleware/api_gateway.py
  app/middleware/api_gateway_authentication.py
  app/middleware/api_gateway_middleware.py
  app/middleware/apigw.py
  app/tests/tests_09/test_geoadmin_header_auth.py
  app/tests/tests_10/test_geoadmin_header_auth.py
Labels: bug

#504 PB-1282: document the new authentication method.
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/paths.yaml
  spec/transaction/tags.yaml
Labels: feature

#506 PB-1281: Disable old authentication for STAC v1
  app/config/settings_prod.py
  app/middleware/rest_framework_authentication.py
  app/tests/tests_10/test_asset_upload_endpoint.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  app/tests/tests_10/test_collections_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
Labels: feature

#505 PB-1360 Improve internal upload workflow
  app/stac_api/admin.py
  app/stac_api/models/general.py
  app/stac_api/serializers/item.py
  app/tests/tests_10/test_external_assets_endpoint.py
Labels: feature
