Repository geoadmin/service-stac, pull requests merged in 2025-02, with the labels that each got.

#509 PB-1091 Fix file size updater
  app/stac_api/management/commands/update_asset_file_size.py
Labels: bug

#512 PB-1279 Batch create endpoint for items/assets
  app/stac_api/serializers/item.py
  app/stac_api/validators_serializer.py
  app/stac_api/views/item.py
  app/tests/tests_09/test_items_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_serializer.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: feature

#513 PB-1331: admin upload large files
  app/stac_api/admin.py
  app/stac_api/models/general.py
  app/stac_api/templates/js/admin/upload.js
  app/stac_api/templates/js/external/crypto-js-4.2.0.min.js
  app/stac_api/templates/style/admin/upload.css
  app/templates/admin/change_form.html
  app/templates/uploadtemplate.html
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
Labels: feature

#516 PB-1279: Fix test
  app/tests/tests_10/test_items_endpoint.py
Labels: feature

#517 New Release v1.32.0 - #minor
  app/config/settings_dev.py
  app/config/settings_prod.py
  app/middleware/api_gateway_middleware.py
  app/middleware/rest_framework_authentication.py
  app/stac_api/admin.py
  app/stac_api/management/commands/update_asset_file_size.py
  app/stac_api/models/general.py
  app/stac_api/serializers/item.py
  app/stac_api/templates/js/admin/upload.js
  app/stac_api/templates/js/external/crypto-js-4.2.0.min.js
  app/stac_api/templates/style/admin/upload.css
  app/stac_api/validators_serializer.py
  app/stac_api/views/item.py
  app/templates/admin/change_form.html
  app/templates/uploadtemplate.html
  app/tests/base_test_admin_page.py
  app/tests/test_admin_page.py
  app/tests/tests_09/test_asset_upload_endpoint.py
  app/tests/tests_09/test_assets_endpoint.py
  app/tests/tests_09/test_collections_endpoint.py
  app/tests/tests_09/test_geoadmin_header_auth.py
  app/tests/tests_09/test_items_endpoint.py
  app/tests/tests_09/test_search_endpoint.py
  app/tests/tests_10/test_asset_upload_endpoint.py
  app/tests/tests_10/test_assets_endpoint.py
  app/tests/tests_10/test_collection_asset_upload_endpoint.py
  app/tests/tests_10/test_collection_assets_endpoint.py
  app/tests/tests_10/test_collections_endpoint.py
  app/tests/tests_10/test_external_assets_endpoint.py
  app/tests/tests_10/test_generic_api.py
  app/tests/tests_10/test_geoadmin_header_auth.py
  app/tests/tests_10/test_item_to_collection_endpoint.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_search_endpoint.py
  app/tests/tests_10/test_serializer.py
  app/tests/utils.py
  spec/components/schemas.yaml
  spec/static/spec/v1/openapi.yaml
  spec/static/spec/v1/openapitransactional.yaml
  spec/transaction/components/schemas.yaml
  spec/transaction/paths.yaml
Labels: new-release

#521 PB-1478 made asset deserialization equivalent to serialization
  app/stac_api/serializers/utils.py
  app/tests/tests_10/test_items_endpoint.py
  app/tests/tests_10/test_serializer.py
Labels: bug
